#! /bin/bash

SRC_DIR="/home/wcc/Source/"
LIB_DIR="/home/wcc/Source/lib/"

function trysubmit_c {
	if make
	then
		./a.out
	fi
}

function config_c_makefile {
	echo WCC_LLIB: ${WCC_LLIB}
	echo "a.out: ${pid}.c" > Makefile
	echo "	gcc -Wall -L${LIB_DIR} -Wl,-rpath=${LIB_DIR} -I${SRC_DIR} $WCC_LLIB ${pid}.c" >> Makefile
}

function config_c_alias {
	alias vih="vi ${pid}.c"
	alias vii="vi Inputs/${pid}"
	alias th="trysubmit_c"
	alias g0="sed -r '/^[ \t]*?\/\//d' $pid.c > 0000.c"
}


	

pid=${1-0000}
echo "Source File: ${pid}.c"
config_c_makefile
echo "Makefile generated."
config_c_alias
echo "command vih vii th g0 is ready."
