#! /bin/bash

function config_java_makefile {
	echo "P${pid}.class: P${pid}.java" > Makefile
	echo "	javac P${pid}.java" >> Makefile
	echo "clean:" >> Makefile
	echo "	rm *.class" >> Makefile
}

function config_java_alias {
	alias vih="vi P${pid}.java"
	alias vii="vi Inputs/${pid}"
	alias th="trysubmit_java"
	alias g0="gMain"
}

function trysubmit_java {
	if make
	then
		java P${pid}
	fi
}

function gMain {
	sed -r '/^[ \t]*?\/\//d' P${pid}.java > .Main.java
	sed -r "s/ P$pid / Main /g" .Main.java > Main.java
	rm .Main.java
}

pid=${1-0000}
echo "Source File: P${pid}.java"
config_java_makefile
config_java_alias

